In [1]:
import os
import subprocess


In [2]:
urls = [
   'https://youtu.be/T71ZyjvCtOA?si=edERKHxJN3pIlwqy',
    'https://youtu.be/ku4k6DQdoDs?si=ihlGALAEGLCv7lVa',
    'https://youtu.be/09839DpTctU?si=LMhr529Vdg_FqZG9',
    'https://youtu.be/YlUKcNNmywk?si=YRI8wiHMaLOosYqf',
    'https://youtu.be/tAGnKpE4NCI?si=T87MMRaSq26y6hFn',
    'https://youtu.be/nyq9r8OYmn0?si=CYwk69ee4SPOPUh0',
    'https://youtu.be/agYzgxruck0?si=uFxvapOusuAjObxQ',
    'https://youtu.be/WeY9hdsmIaQ?si=F5hQtkWJPrQbwCnu',
    'https://youtu.be/h1PMLoiiliA?si=-NX-ax7XagpT2Ni0',
    'https://youtu.be/4mLAIoqLYuQ?si=IrlRmOh0hG4kqp0t',
    'https://youtu.be/wiO2VJCMgUo?si=Lw5uZHy1maMxdDCE',
    'https://youtu.be/vx2u5uUu3DE?si=_KHthhvOK5c-yteE',
    'https://youtu.be/NvR60Wg9R7Q?si=U1pvdTmdyMHKdxOC',
    'https://youtu.be/QkF3oxziUI4?si=_sdZ6M8qL65XFyJl',
    'https://youtu.be/CD-E-LDc384?si=vS2SznV8IhrGp4GP',
    'https://youtu.be/E0ozmU9cJDg?si=det63ZvlpM9ZtWkM',
    'https://youtu.be/1w7OgIMMRc4?si=AYB26yXb9amLiq3W',
    'https://youtu.be/hTWKbfoikeg?si=rT8bgT2i9k02plUk',
    'https://youtu.be/fJ9rUzIMcZQ?si=VJNH4FsVujFvU1Iw',
    'https://youtu.be/8SbUC-UaAxE?si=BJHG9nqAD6qqWIKe',
    'https://youtu.be/v2AC41dglnM?si=0PldLN7vKvj0g69K',
    'https://youtu.be/89dGC8de0CA?si=mLE-rkG_xbWZrUqY',
    'https://youtu.be/7f3EGjRxxNI?si=Ue96BY0RtDkcApIq',
    'https://youtu.be/x3sFsHrUyLQ?si=eUC6vGUH7kiYjn-w',
    'https://youtu.be/CWUGikRxGQs?si=VmabBwHZor2eR0hq',
    'https://youtu.be/k8gx-C7GCGU?si=8GiupYewWxv7JaFZ',
    'https://youtu.be/EwLMA5XYnKI?si=7k85ic6s94jxtHiD',
    'https://youtu.be/1-1TGNmQqZA?si=bns4230juoCXeLZp',
    'https://youtu.be/fGubAEGT8f4?si=yoMAjVAJbp6o4ghR',
    'https://youtu.be/atWpuwRcMoc?si=66-_xEnIlcypoUEH',
    'https://youtu.be/Opxhh9Oh3rg?si=6ZN3OJJlLyD1wN7O',
    'https://youtu.be/igvP806798U?si=QEnuQ-cMsK_d-GzP',
    'https://youtu.be/pAgnJDJN4VA?si=NPt3drmJW8RbYUmu',
    'https://youtu.be/A_MjCqQoLLA?si=veiqQNnU7CigghyF',
    'https://youtu.be/r00ikilDxW4?si=1TgdCs3D9ap_Fud9',
    'https://youtu.be/pGhwBFYtn1s?si=oYhRexTVzpNxvuh-',
    'https://youtu.be/Soa3gO7tL-c?si=dqTkGU8dDMU-l-aj',
    'https://youtu.be/eVTXPUF4Oz4?si=oepvB4oxXP3nyctC',
    'https://youtu.be/FmE9DQgdNm8?si=C0F2M7pcinHdIt8b',
    'https://youtu.be/eCCT-cgMHDc?si=IazT24Och4gL7gkj'
    
]




In [3]:
save_path = "C:/Users/acann/OneDrive/Desktop/ml project/datasets/rock"
os.makedirs(save_path, exist_ok=True)

In [4]:
for i, url in enumerate(urls, start=1):
    try:
        subprocess.run([
            "yt-dlp", "-x", "--audio-format", "mp3",
            "-o", f"{save_path}/song_{i}.%(ext)s", url
        ], check=True)
        print(f"Downloaded: song_{i}")
    except subprocess.CalledProcessError as e:
        print(f"Failed to download {url} - {e}")

Downloaded: song_1
Downloaded: song_2
Downloaded: song_3
Downloaded: song_4
Downloaded: song_5
Downloaded: song_6
Downloaded: song_7
Downloaded: song_8
Downloaded: song_9
Downloaded: song_10
Downloaded: song_11
Downloaded: song_12
Downloaded: song_13
Downloaded: song_14
Downloaded: song_15
Downloaded: song_16
Downloaded: song_17
Downloaded: song_18
Downloaded: song_19
Downloaded: song_20
Downloaded: song_21
Downloaded: song_22
Downloaded: song_23
Downloaded: song_24
Downloaded: song_25
Downloaded: song_26
Downloaded: song_27
Downloaded: song_28
Downloaded: song_29
Downloaded: song_30
Downloaded: song_31
Downloaded: song_32
Downloaded: song_33
Downloaded: song_34
Downloaded: song_35
Downloaded: song_36
Downloaded: song_37
Downloaded: song_38
Downloaded: song_39
Downloaded: song_40


In [5]:
pip install librosa

^C
Note: you may need to restart the kernel to use updated packages.
   ---------------------------------------- 0.0/1.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.0 MB ? eta -:--:--
   ---------- ----------------------------- 0.3/1.0 MB ? eta -:--:--
   ---------- ----------------------------- 0.3/1.0 MB ? eta -:--:--
   ---------- ----------------------------- 0.3/1.0 MB ? eta -:--:--
   -------------------- ------------------- 0.5/1.0 MB 417.9 kB/s eta 0:00:02
   -------------------- ------------------- 0.5/1.0 MB 417.9 kB/s eta 0:00:02
   ------------------------------ --------- 0.8/1.0 MB 472.9 kB/s eta 0:00:01
   ---------------------------------------- 1.0/1.0 MB 569.0 kB/s eta 0:00:00

   ----------------- ---------------------- 4/9 [standard-aifc]
   -------------------------- ------------- 6/9 [pooch]
   -------------------------- ------------- 6/9 [pooch]
   -------------------------

In [2]:
import librosa, soundfile as sf, glob, os

In [7]:

input_path = r"C:\Users\acann\OneDrive\Desktop\ml project\datasets\rock"

for mp3 in glob.glob(os.path.join(input_path, "*.mp3")):
    try:
        y, sr = librosa.load(mp3, sr=44100, mono=True)
        wav_path = os.path.splitext(mp3)[0] + ".wav"
        sf.write(wav_path, y, sr)
        print(f"Converted: {os.path.basename(wav_path)}")
    except Exception as e:
        print(f"Failed {mp3} - {e}")


Converted: song_1.wav
Converted: song_10.wav
Converted: song_11.wav
Converted: song_12.wav
Converted: song_13.wav
Converted: song_14.wav
Converted: song_15.wav
Converted: song_16.wav
Converted: song_17.wav
Converted: song_18.wav
Converted: song_19.wav
Converted: song_2.wav
Converted: song_20.wav
Converted: song_21.wav
Converted: song_22.wav
Converted: song_23.wav
Converted: song_24.wav
Converted: song_25.wav
Converted: song_26.wav
Converted: song_27.wav
Converted: song_28.wav
Converted: song_29.wav
Converted: song_3.wav
Converted: song_30.wav
Converted: song_31.wav
Converted: song_32.wav
Converted: song_33.wav
Converted: song_34.wav
Converted: song_35.wav
Converted: song_36.wav
Converted: song_37.wav
Converted: song_38.wav
Converted: song_39.wav
Converted: song_4.wav
Converted: song_40.wav
Converted: song_5.wav
Converted: song_6.wav
Converted: song_7.wav
Converted: song_8.wav
Converted: song_9.wav


In [4]:
import numpy as np
import librosa

In [5]:
input_path = r"C:\Users\acann\OneDrive\Desktop\ml project\datasets\rock"
output_path = os.path.join(input_path, "processed")
os.makedirs(output_path, exist_ok=True)

In [6]:
DURATION = 30        # seconds
SR = 44100
SAMPLES_30S = SR * DURATION

In [7]:
import random

In [8]:
for wav_file in glob.glob(os.path.join(input_path, "*.wav")):
    try:
        y, sr = librosa.load(wav_file, sr=SR, mono=True)
        total_len = len(y)

        if total_len > SAMPLES_30S:
            start = random.randint(0, total_len - SAMPLES_30S)
            y = y[start:start + SAMPLES_30S]
        else:
            y = librosa.util.fix_length(y, size=SAMPLES_30S)

        max_val = np.max(np.abs(y))
        if max_val != 0:
            y = y / max_val

        base = os.path.basename(wav_file)
        save_path = os.path.join(output_path, base)
        sf.write(save_path, y, sr)
        print(f" Processed: {base}")

    except Exception as e:
        print(f" Failed {wav_file} - {e}")

 Processed: song_1.wav
 Processed: song_10.wav
 Processed: song_11.wav
 Processed: song_12.wav
 Processed: song_13.wav
 Processed: song_14.wav
 Processed: song_15.wav
 Processed: song_16.wav
 Processed: song_17.wav
 Processed: song_18.wav
 Processed: song_19.wav
 Processed: song_2.wav
 Processed: song_20.wav
 Processed: song_21.wav
 Processed: song_22.wav
 Processed: song_23.wav
 Processed: song_24.wav
 Processed: song_25.wav
 Processed: song_26.wav
 Processed: song_27.wav
 Processed: song_28.wav
 Processed: song_29.wav
 Processed: song_3.wav
 Processed: song_30.wav
 Processed: song_31.wav
 Processed: song_32.wav
 Processed: song_33.wav
 Processed: song_34.wav
 Processed: song_35.wav
 Processed: song_36.wav
 Processed: song_37.wav
 Processed: song_38.wav
 Processed: song_39.wav
 Processed: song_4.wav
 Processed: song_40.wav
 Processed: song_5.wav
 Processed: song_6.wav
 Processed: song_7.wav
 Processed: song_8.wav
 Processed: song_9.wav


In [8]:
from scipy.fft import rfft, rfftfreq

In [17]:
input_path  = r"C:\Users\acann\OneDrive\Desktop\ml project\datasets\rock\processed" 
output_path = r"C:\Users\acann\OneDrive\Desktop\ml project\datasets\rock\features_XM"
os.makedirs(output_path, exist_ok=True)

SR = 44100
DURATION = 30
SAMPLES_30S = SR * DURATION

n_mels = 20
mel_edges = librosa.mel_frequencies(n_mels=n_mels + 1, fmin=0.0, fmax=2000.0)
xm_bands = [(mel_edges[i], mel_edges[i + 1]) for i in range(len(mel_edges) - 1)]

In [18]:
def extract_xm_features(wav_path):
    y, _ = librosa.load(wav_path, sr=None, mono=True)  # no resampling, already 44.1kHz mono
    Y = np.abs(rfft(y))
    freqs = rfftfreq(len(y), 1.0 / SR)

    feats = []
    for low, high in xm_bands:
        mask = (freqs >= low) & (freqs < high)
        feats.append(Y[mask].mean() if mask.any() else 0.0)

    x = np.array(feats, dtype=float)
    norm = np.linalg.norm(x)
    if norm > 0:
        x /= norm
    return x

In [19]:
import glob
import pandas as pd

In [20]:
rows = []
for wav_file in glob.glob(os.path.join(input_path, "*.wav")):
    try:
        feat = extract_xm_features(wav_file)
        base = os.path.basename(wav_file)
        rows.append([base, *feat])
        print(f"{base}")
    except Exception as e:
        print(f"{wav_file} - {e}")

cols = ["file"] + [f"f{i+1}" for i in range(len(xm_bands))]
df = pd.DataFrame(rows, columns=cols)
csv_path = os.path.join(output_path, "features_XM.csv")
df.to_csv(csv_path, index=False)

print(f"\n Saved {csv_path}  (shape = {df.shape})")

✅ song_1.wav
✅ song_10.wav
✅ song_11.wav
✅ song_12.wav
✅ song_13.wav
✅ song_14.wav
✅ song_15.wav
✅ song_16.wav
✅ song_17.wav
✅ song_18.wav
✅ song_19.wav
✅ song_2.wav
✅ song_20.wav
✅ song_21.wav
✅ song_22.wav
✅ song_23.wav
✅ song_24.wav
✅ song_25.wav
✅ song_26.wav
✅ song_27.wav
✅ song_28.wav
✅ song_29.wav
✅ song_3.wav
✅ song_30.wav
✅ song_31.wav
✅ song_32.wav
✅ song_33.wav
✅ song_34.wav
✅ song_35.wav
✅ song_36.wav
✅ song_37.wav
✅ song_38.wav
✅ song_39.wav
✅ song_4.wav
✅ song_40.wav
✅ song_5.wav
✅ song_6.wav
✅ song_7.wav
✅ song_8.wav
✅ song_9.wav

 Saved C:\Users\acann\OneDrive\Desktop\ml project\datasets\rock\features_XM\features_XM.csv  (shape = (40, 21))


In [44]:
import pandas as pd

In [45]:
df=pd.read_csv(r"C:\Users\acann\OneDrive\Desktop\ml project\processed and feature extracted_final.csv")

In [46]:
import numpy as np

In [47]:
df = df.replace('-', np.nan)
df = df.dropna()
X = df.iloc[:, 2:].values.astype(float)

In [48]:
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

In [49]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [50]:
# print(df.dtypes)
print(df.head())

                                           File name      genre        f1  \
0  Hindustani Classical Vocal - Bandish - Sachi K...  classical  0.055238   
1  Zindagi Se Badi Saza Hi Nahin ｜ Relaxing Sitar...  classical  0.008259   
2  Hindustani Classical Vocal ｜ Kalpana Zokarkar｜...  classical  0.129947   
3  Indian Classical Vocal ｜ Manjusha Kulkarni Pat...  classical  0.042809   
4  Raga Darbari Kanhada - Pandit Jasraj (Album： T...  classical  0.058416   

            f2        f3        f4        f5        f6        f7        f8  \
0   0.34256995  0.158805  0.406750  0.083513  0.114141  0.211138  0.366079   
1  0.015218734  0.107816  0.413347  0.316100  0.279544  0.274531  0.367286   
2   0.46471637  0.161825  0.251175  0.256754  0.341654  0.200203  0.207060   
3     0.431102  0.195693  0.307134  0.232218  0.286155  0.080349  0.233229   
4   0.46689004  0.280672  0.254930  0.254814  0.269564  0.313488  0.278635   

   ...       f11       f12       f13       f14       f15       f16  

In [51]:
k = 4
kmeans = KMeans(n_clusters=k, random_state=42)
clusters = kmeans.fit_predict(X_scaled)

C:\Users\acann\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


In [52]:
df["cluster"] = clusters

In [53]:
sil_score = silhouette_score(X_scaled, clusters)
print(f" K-Means completed with {k} clusters")
print(f" Silhouette Score: {sil_score:.4f}")

 K-Means completed with 4 clusters
 Silhouette Score: 0.4945


In [54]:
y = df['genre']

In [55]:
from sklearn.metrics import rand_score, adjusted_rand_score, normalized_mutual_info_score

RI = rand_score(y, clusters)
ARI = adjusted_rand_score(y, clusters)
NMI = normalized_mutual_info_score(y, clusters)

print("Rand Index (RI):", RI)
print("Adjusted Rand Index (ARI):", ARI)
print("Normalized Mutual Info (NMI):", NMI)

Rand Index (RI): 0.4731132075471698
Adjusted Rand Index (ARI): 0.11004043835781181
Normalized Mutual Info (NMI): 0.3188523591009973


In [56]:
def purity_score(y_true, y_pred):
    contingency = pd.crosstab(y_true, y_pred)
    return np.sum(np.max(contingency.values, axis=0)) / np.sum(contingency.values)

purity = purity_score(y, clusters)
print("Purity:", round(purity, 4))

Purity: 0.4312


In [14]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix

df_eval = pd.DataFrame({"true": y, "cluster": clusters})

mapping = {}

for c in df_eval["cluster"].unique():
    common = df_eval[df_eval["cluster"] == c]["true"].mode()[0]
    mapping[c] = common

print("Cluster → Genre mapping:", mapping)

df_eval["predicted"] = df_eval["cluster"].map(mapping)
cm = confusion_matrix(df_eval["true"], df_eval["predicted"],
                      labels=["classical", "jazz", "rock", "pop"])
print("\nConfusion Matrix:\n", cm)


Cluster → Genre mapping: {np.int32(1): 'classical', np.int32(2): 'pop', np.int32(3): 'pop', np.int32(0): 'pop'}

Confusion Matrix:
 [[40  0  0  0]
 [40  0  0  0]
 [40  0  0  0]
 [11  0  0 29]]


In [15]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import rand_score
import random

In [19]:
df["genre"].value_counts()

genre
classical    40
pop          40
jazz         40
rock         40
Name: count, dtype: int64

In [20]:
df["genre"] = df["genre"].astype(str).str.strip().str.lower()

In [21]:
df["genre"].value_counts()

genre
classical    40
pop          40
jazz         40
rock         40
nan           3
Name: count, dtype: int64

In [27]:
from sklearn.metrics import silhouette_score

In [31]:
csv_path = r"C:\Users\acann\OneDrive\Desktop\ml project\processed and feature extracted_final.csv"
df = pd.read_csv(csv_path)

In [32]:
print(df["genre"].unique())


['classical' 'pop' 'jazz' 'rock' nan]


In [33]:
df = df.dropna(subset=["genre"]).reset_index(drop=True)

In [34]:
print(df["genre"].unique())
print(df.shape)

['classical' 'pop' 'jazz' 'rock']
(160, 22)


In [35]:
X = df.iloc[:, 2:].astype(float).values  
y = df["genre"].values                   

In [36]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


In [37]:
from sklearn.decomposition import PCA

pca = PCA(n_components=10)
X_pca = pca.fit_transform(X_scaled)


In [38]:
import random
import numpy as np

genres = df["genre"].unique()

initial_centroids = []
for g in genres:
    idx = df[df["genre"] == g].index.tolist()
    chosen = random.choice(idx)
    initial_centroids.append(X_pca[chosen])

initial_centroids = np.array(initial_centroids)

In [39]:
kmeans = KMeans(n_clusters=4, init=initial_centroids, n_init=1, random_state=42)
clusters = kmeans.fit_predict(X_pca)

df["cluster"] = clusters


C:\Users\acann\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


In [40]:
from sklearn.metrics import rand_score, adjusted_rand_score, normalized_mutual_info_score

RI = rand_score(y, clusters)
ARI = adjusted_rand_score(y, clusters)
NMI = normalized_mutual_info_score(y, clusters)

print("Rand Index (RI):", RI)
print("Adjusted Rand Index (ARI):", ARI)
print("Normalized Mutual Info (NMI):", NMI)


Rand Index (RI): 0.7549528301886792
Adjusted Rand Index (ARI): 0.36539015592407775
Normalized Mutual Info (NMI): 0.4452294911579203


In [41]:
sil_score = silhouette_score(X_scaled, clusters)
print(f" Silhouette Score: {sil_score:.4f}")

 Silhouette Score: 0.1823


In [42]:
def purity_score(y_true, y_pred):
    contingency = pd.crosstab(y_true, y_pred)
    return np.sum(np.max(contingency.values, axis=0)) / np.sum(contingency.values)

purity = purity_score(y, clusters)
print("Purity:", round(purity, 4))

Purity: 0.6688


In [43]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix

df_eval = pd.DataFrame({"true": y, "cluster": clusters})
mapping = {}
for c in df_eval["cluster"].unique():
    common = df_eval[df_eval["cluster"] == c]["true"].mode()[0]
    mapping[c] = common
print("Cluster → Genre mapping:", mapping)
df_eval["predicted"] = df_eval["cluster"].map(mapping)

cm = confusion_matrix(df_eval["true"], df_eval["predicted"],
                      labels=["classical", "jazz", "rock", "pop"])

print("\nConfusion Matrix:\n", cm)


Cluster → Genre mapping: {np.int32(1): 'classical', np.int32(3): 'rock', np.int32(2): 'jazz', np.int32(0): 'pop'}

Confusion Matrix:
 [[19  5 16  0]
 [ 0 39  1  0]
 [ 1 12 27  0]
 [11  1  6 22]]
